packages:
  - "apps/*"
  - "packages/*"

patchedDependencies:
  expo-modules-jsi: apps/mobile/patches/expo-modules-jsi.patch

catalog:
  effect: 4.0.0-beta.102
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
  vitest: 4.1.10
  vite-plus: 0.2.7

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
