export { MAX_FRAME_PAYLOAD_BYTES } from "@tunnel/protocol";

export const DEFAULT_REQUEST_TIMEOUT_MS = 30_000;
export const DEFAULT_MAX_PENDING_REQUESTS = 32;
export const DEFAULT_MAX_REQUEST_BYTES = 52_428_800;
export const DEFAULT_MAX_RESPONSE_BYTES = 104_857_600;
export const DEFAULT_HEARTBEAT_INTERVAL_MS = 20_000;
export const DEFAULT_HEARTBEAT_TIMEOUT_MS = 60_000;
export const TOKEN_TTL_SECONDS = 900;
