/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TunnelsRouteImport } from './routes/tunnels'
import { Route as AssetsUploadSplatRouteImport } from './routes/assets/upload/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TunnelsRoute = TunnelsRouteImport.update({
  id: '/tunnels',
  path: '/tunnels',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsUploadSplatRoute = AssetsUploadSplatRouteImport.update({
  id: '/assets/upload/$',
  path: '/assets/upload/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tunnels': typeof TunnelsRoute
  '/assets/upload/$': typeof AssetsUploadSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tunnels': typeof TunnelsRoute
  '/assets/upload/$': typeof AssetsUploadSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tunnels': typeof TunnelsRoute
  '/assets/upload/$': typeof AssetsUploadSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/domains'
    | '/login'
    | '/register'
    | '/tunnels'
    | '/assets/upload/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/domains'
    | '/login'
    | '/register'
    | '/tunnels'
    | '/assets/upload/$'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/domains'
    | '/login'
    | '/register'
    | '/tunnels'
    | '/assets/upload/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  DomainsRoute: typeof DomainsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TunnelsRoute: typeof TunnelsRoute
  AssetsUploadSplatRoute: typeof AssetsUploadSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tunnels': {
      id: '/tunnels'
      path: '/tunnels'
      fullPath: '/tunnels'
      preLoaderRoute: typeof TunnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/upload/$': {
      id: '/assets/upload/$'
      path: '/assets/upload/$'
      fullPath: '/assets/upload/$'
      preLoaderRoute: typeof AssetsUploadSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  DomainsRoute: DomainsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TunnelsRoute: TunnelsRoute,
  AssetsUploadSplatRoute: AssetsUploadSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
